name: pipeline

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      UPDATE_FILE_PATH: "scripts/update_readme.sh"
      COMMITPUSH_FILE_PATH: "scripts/commit_push.sh"
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md file
        run: |
          bash "${UPDATE_FILE_PATH}"
      - name: Commit and push new README.md file
        run: |
          bash "${COMMITPUSH_FILE_PATH}"

  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          bash scripts/app_build.sh
      - name: Upload to S3 bucket
        uses: tpaschalis/s3-sync-action@master
        with:
          args: --acl public-read --recursive
        env:
          AWS_S3_BUCKET: bargs.link
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
          FILE: "dist"
      - name: Invalidate AWS CloudFront distribution
        uses: awact/cloudfront-action@master
        env:
          SOURCE_PATH: "/"
          AWS_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
